### ISSUE TITLE
How do I run skepticoin-mine in the background on my Linux machine

### ISSUE THREAD

**Issue by metaperl** [skepticoin/skepticoin#10]
`nohup skepticoin-mine &` does not appear to do any mining..... I aborted an earlier `nohup skepticoin-mine` with Control-C which may have broken something.

**Comment by hunter-bidens-laptop** [comment]
Are you doing all the python steps before and running this inside venv?

**Comment by sashimi-houdini** [comment]
I'm not aware of any magic that should prevent running in nohup. Doesn't nohup by default output to some file `nohup.out`? Is there anything in there that may be a hint? Did running without `nohup` work for you?

Personally I like to run the miner in a `screen` session which can then be detached from using ^a-d; this allows for later re-attaching if you want to see what's going on.
