### ISSUE TITLE
skepticoin is dead

### ISSUE THREAD

**Issue by refacktor** [skepticoin/skepticoin#106]
I stopped paying attention to skepticoin over the summer... now I went to look and to count my SKEPTIs and found two things, 1) my miner script died sometime in August with a MemoryError, and 2) the script won't restart because there is only one peer on the network and it isn't responding (I guess all the peers also got a MemoryError?)

If anybody has a peer still running, please share the IP address so we can reconnect ;-)

**Comment by sashimi-houdini** [comment]
It's not dead for me.

The IP addresses from the pastebin are enough for me. Are they not loaded for you? Could you try throwing away your local `peers.json`? And if that remedies the problem, we should probably add peers from the pastebin and similar location on each start of skepticoin, at least for now.
