### ISSUE TITLE
Never updates the chain

### ISSUE THREAD

**Issue by KevinBatdorf** [skepticoin/skepticoin#117]
After seeing some activity here yesterday I tried to start up the script again to see what was new. I ran:

```
pip install --upgrade pip
pip install --upgrade skepticoin
skepticoin-mine
```

I'm not super familiar with python so maybe I didn't even update properly?

> Waiting for fresh chain (your chain is 10,236,836 seconds too old for my tastes)

![Screen Shot 2022-05-29 at 2 58 30 PM](https://user-images.githubusercontent.com/1478421/170887141-54cfe3e7-4f3d-4a51-9c9a-89ec19b32a60.png)

**Comment by atramos** [comment]
Most of the latest fixes have not been merged yet. I'm using the branch from kryptocurrency/hotfix ... do a git clone and then Python setup.py install.

**Comment by atramos** [comment]
Actually, first try just deleting your chain.cache and peers.json files and restarting.

**Comment by KevinBatdorf** [comment]
I deleted the two files and it's running now, but still seems like it's stuck. I can wait until the updates are published though. No rush. 
![Screen Shot 2022-05-29 at 4 35 10 PM](https://user-images.githubusercontent.com/1478421/170890524-3e922d2e-9ddc-4402-9084-d9ea24266a8d.png)
 
Can I just delete the directory and clone the repo? Where's the important data stored?

**Comment by KevinBatdorf** [comment]
Does the "too old" message imply I didn't delete the cache properly? I'll try again.

**Comment by atramos** [comment]
Peers are connected and the age number is decreasing. Looks good just wait until it catches up.

**Comment by atramos** [comment]
> 
> Can I just delete the directory and clone the repo? Where's the important data stored?

The important file you don't want to delete is wallet.json

**Comment by KevinBatdorf** [comment]
Seeing this error now:

![Screen Shot 2022-05-30 at 3 24 37 PM](https://user-images.githubusercontent.com/1478421/171050377-d78b0efc-d311-42a8-9e0f-40b81692d79a.png)

```
Traceback (most recent call last):
  File "/usr/local/bin/skepticoin-mine", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/skepticoin/scripts/mine.py", line 6, in main
    miner_watcher()
  File "/usr/local/lib/python3.9/site-packages/skepticoin/mining.py", line 123, in __call__
    self.public_key = self.wallet.get_annotated_public_key("reserved for potentially mined block")
  File "/usr/local/lib/python3.9/site-packages/skepticoin/wallet.py", line 49, in get_annotated_public_key
    public_key = self.unused_public_keys.pop()
IndexError: pop from empty list
```

**Comment by atramos** [comment]
Thanks for reporting back your findings. I believe you are experiencing a bug that may have been introduced in @sashimi-houdini 's commit #0311fde0. Try this: downgrade to the previous version (`pip install skepticoin==0.1.20`) and delete your wallet.json. Normally you should NEVER delete your wallet.json but I think in your specific situation it will help. Your blockchain is already at 2022-05-23 so don't delete your chain.cache, it's already very close to catching up and will save you several minutes if you keep it. 

@sashimi-houdini I only did some very quick testing but it seems that as a result of #0311fde0, the miner starts prematurely before finishing the download of the chain.

**Comment by KevinBatdorf** [comment]
That worked and the miner started, but now if I run `skepticoin-balance` I get this:

```
Reading cached chain
Starting networking peer in background
Loading initial list of 17 peers
NETWORK - 0 connected peers:
CHAIN - Height = 292000, Date/time = 2022-05-30T10:57:16

Waiting for fresh chain
Chain up to date
0.0 SKEPTI at h. 292551, 2022-05-31T01:25:23
Waiting for networking thread to exit.
```

**Comment by atramos** [comment]
The balance is tied to your `wallet.json`. Your previous `wallet.json` may have shown a balance but I believe it was not tenable - i.e. you had inadvertently forked the chain by mining from an older height, as a result of this possible new bug in v0.1.21.

**Comment by KevinBatdorf** [comment]
I had the miner running for months though, so all of that is gone?

**Comment by atramos** [comment]
Can you try swapping out the original `wallet.json` and restarting with `v0.1.20`? The chain has a big gap from April 9th until a few days ago when I started poking around. I wonder if it had forked even prior to April.

**Comment by KevinBatdorf** [comment]
Not looking good? 
![Screen Shot 2022-05-31 at 1 46 37 AM](https://user-images.githubusercontent.com/1478421/171101487-6458a9ea-191c-4f1c-9ada-00c71a0d1ba0.png)

**Comment by atramos** [comment]
The output of `skepticoin-balance` is good news, so don't lose that `wallet.json`.  The bad news is that you have mined all 10,000 keys from that wallet, so you can't mine anymore until either PR #113 is released. As a workaround you could continue mining with a brand-new `wallet.json` and then merge the two wallets when the merge functionality becomes available (#115)

**Comment by KevinBatdorf** [comment]
I'll just wait on #113. It's no big deal. Thanks for looking into it.

**Comment by atramos** [comment]
I've made some more fixes over the last few days. Now just waiting for @sashimi-houdini to make new release.

**Comment by KevinBatdorf** [comment]
Could you walk me through steps getting back in?

**Comment by sashimi-houdini** [comment]
Some notes from the master:

1. @KevinBatdorf, you have disappointed me. We still haven't checked that box of an early adopter losing an insane amount of coins (in your case some 0.5% of the eternal global supply). Could you take one for the team and do that for me?
2. @refacktor's notes are correct: you got a bit greedy and tried to mine more than 100,000 SKEPTI. This is currently only supported if you manually create a new wallet. Moving your old wallet manually to a "safe location" should do the trick. This has the additional benefit of helping out with point 1.

The release of Skepticoin 3.0 I did yesterday was intentionally without any new features (in honor of Web 3.0) though I even messed that up accidentally and a tiny change got introduced. The merge of #113 that I also did yesterday should be in a pip-installable version soonish if you want to skip step 2 above.

**Comment by KevinBatdorf** [comment]
> you have disappointed me.

If you're saying there's no path to recovery that's fine, but it's pretty weird to say I've disappointed you.

> you got a bit greedy and tried to mine more than 100,000 SKEPTI

Not sure how something can be greedy if there was no interaction on my end. I literally left it on in the background and didn't look at it. I wasn't aware i needed to monitor it and make sure I didn't hit a limit. Sounds more like a poor design choice?

> Could you take one for the team and do that for me?

If you're asking me to trash the coins and move on with my life, then sure. I couldn't care less. I was just joining in the game for fun. I didn't realize the project was full of bugs and maintained by someone without much development experience.

**Comment by refacktor** [comment]
@KevinBatdorf if you didn't lose the wallet.json you should still have your 100,000 coins. Your sarcasm detector may need recalibration though. Sashimi was just saying we need someone to step up and be like the James Howells of Skepticoin: We secretly hope you tossed your hard drive in the trash.

**Comment by KevinBatdorf** [comment]
I still have the wallet.json file, yes. The attempt at humor was inappropriate at best given the circumstances.
