### ISSUE TITLE
flake8 on pre-commit hook doesn't catch some errors

### ISSUE THREAD

**Issue by refacktor** [skepticoin/skepticoin#132]
For example, the fix in commit 0ae787ae5b4d199cda001119ee8bdd9428f12b76:

The parent commit throws an E275 in the github flake8 action.

Running locally as part of commit or with `pre-commit run --all-files` does not produce any error.

**Comment by vanschelven** [comment]
could be a discrepancy of `flake8` versions (or dependencies thereof). Might even be the case that if your local virtualenv is activated (and contains an older version of `flake8`) and you run `pre-commit` from within the virtualenv, that flake8 is used from within there.
