### ISSUE TITLE
How can I contribuate?

### ISSUE THREAD

**Issue by ArielaRfa** [skepticoin/skepticoin#134]
Hello guys ,I started coding and I would like to start contributing on projects but I don't know which project would be ideal for a junior. I am open to all recommendations.

Thank you all

**Comment by refacktor** [comment]
You should "Self-select" based on your skillset, interest, and time available: check all the issues currently open and see which one makes the most sense to you and try to fix it. For example I enjoy making code run faster, so I may look at #130 or #80 or #31 when I have time. If you enjoy making programs more user-friendly you could look at #97.
