### ISSUE TITLE
empty blockchain file after execution interrupted prevents re-start

### ISSUE THREAD

**Issue by atramos** [skepticoin/skepticoin#23]
If you kill the skepticoin process abruptly (e.g. like when you get impatient waiting for it to download the chain), it sometimes creates an empty (0-bytes) blockchain file which in turn prevents re-start.

As a workaround, you can just remove the empty file in the chain/ directory.

**Comment by sashimi-houdini** [comment]
The mentioned workaround is still required (I didn't feel like deleting files from disk) but the fix I just pushed at least tells you which file is corrupted
