### ISSUE TITLE
More (interesting) stats per second for mining

### ISSUE THREAD

**Issue by lk16** [skepticoin/skepticoin#27]
I am thinking about showing more mining stats per second, but that won't fit on one line. Showing one line per second may not be that interesting anyway, because some stats rarely change. What do you think about using multiple lines for stat output per second?

I will put more details probably tomorrow.

**Comment by sashimi-houdini** [comment]
> What do you think about using multiple lines for stat output per second?

I have no fundamental objection against it.

**Comment by atramos** [comment]
I think the per-second log is great when you're running interactively to get a feel for the process, but it's slightly inconvenient when running in the background as a server process. Would be great to have a "server mode" that just logs when something important happens.

**Comment by sashimi-houdini** [comment]
@atramos remark is also reflected in #32

**Comment by atramos** [comment]
@lk16 can we close this one? I think we already got "more interesting stats per second" as part of multi-mining

**Comment by atramos** [comment]
I'll go ahead and close it, please feel free to reopen it if needed.
