### ISSUE TITLE
Multi-mine can corrupt peers.json; leading to a disconnect from the P2P network

### ISSUE THREAD

**Issue by sashimi-houdini** [skepticoin/skepticoin#28]
Observed behavior: all skepticoin-xxx commands start reporting very low numbers of peers. (for non-listening nodes:
likely 0; listening nodes might actually still have some incoming connections that keep them in the network, I didn't
research further)

Hypothesized cause: multiple processes writing to `peers.json` at the same time, corrupting the file.

Workaround: remove `peers.json` and restart your command (but don't multi-mine for now).

Proper solution(s) (preferably both in parallel in separate PRs):

* there should be only one process writing to `peers.json` at a time.
* properly research / deeply think about other touching of the file system, and how similar corruption could occur for
  other files too.
* add some robustness around the reading of `peers.json`... any failure to read or parse that file should probably lead to a loud and observable error, rather than the implicit peer-disconnect that we do now.

**Comment by sashimi-houdini** [comment]
@lk16 and @dend456 are probably interested

**Comment by sashimi-houdini** [comment]
This showed up as `Disconnecting remote peer Extra data` for me in the logs (but depending on the precise nature of the file's corruption the error message may differ)

**Comment by sashimi-houdini** [comment]
> properly research / deeply think about other touching of the file system, and how similar corruption could occur for
other files too.

After some thought: rather than going over all of the networking code, and introducing locks everywhere, we should [take the comments made here more seriously](https://github.com/skepticoin/skepticoin/pull/26#issuecomment-843524189). That is: the underlying problem is that in the new miner 1 networking thread is being started per miner process. That's simply a design that is going to bite us in various ways. The real solution: have a single networking thread for the case of multi-mining. (And come up with a mechanism such that the various miner processes each have access to the latest block information).

**Comment by nitomitopa** [comment]
Why not use sqlite instead of a json file?

**Comment by lk16** [comment]
> Why not use sqlite instead of a json file?

The way we store the data is not the problem, sashimi went with the simplest solution that works. 
The problem is how we access the file. If we access it from one place (use a single networking thread), that is a way cleaner and maintainable solution.

**Comment by lk16** [comment]
I am [working](https://github.com/lk16/skepticoin/tree/miner-race-conditions) on a fix to this issue.

**Comment by sashimi-houdini** [comment]
> Why not use sqlite instead of a json file?

@lk16 's answer ("the way we store the data is not the problem") is the correct one, although your suggestion is probably independently a good idea.

**Comment by lk16** [comment]
This will be solved by #35
