### ISSUE TITLE
Chain freshness should be more clear

### ISSUE THREAD

**Issue by sashimi-houdini** [skepticoin/skepticoin#30]
The message "waiting for fresh chain" does (apparently) not provide enough information for people to figure out for themselves whether there's any progress being made. I know this because a lot of people ask me what to do and how long the waiting is expected to take.

It should be more clear how many minutes/hours/days your chain is away from the present time.

It could be good to consider _removing_ some info from the "waiting for fresh chain" message also, it's currently quite cluttered.

**Comment by atramos** [comment]
Why does the "waiting for fresh chain" take as long as it does? I imagine if you parcel out the download among all the peers, it should be about as fast as a Torrent.

**Comment by sashimi-houdini** [comment]
> Why does the "waiting for fresh chain" take as long as it does?

Because it was written as "the simplest thing that could possibly work", and tested against the chain when it had a couple of thousands of blocks :smile: 

In particular: blocks are downloaded one by one, from a single other peer at a time, on which no problem detection is done.

It also follows the simple "blocks first" approach, rather than a headers-first approach. See https://developer.bitcoin.org/devguide/p2p_network.html#headers-first for something more advanced.

All of that is a separate issue though (that I'm happy to take PRs for)

**Comment by atramos** [comment]
This issue has been resolved. Current release prints the chain height and corresponding timestamp. It also suppresses duplicates, making it less cluttered.
