### ISSUE TITLE
Mining doesn't work

### ISSUE THREAD

**Issue by hunter-bidens-laptop** [skepticoin/skepticoin#4]
Command ```skepticoin-mine``` runs, but results in the following loop:

![image](https://user-images.githubusercontent.com/83688753/117316721-75aebc80-ae4e-11eb-83a5-58b45fada0a6.png)

No mentions of mining-related activities or wallet balance as in the readme.

**Comment by hunter-bidens-laptop** [comment]
I am a dumb. Just needed to wait longer.

**Comment by sashimi-houdini** [comment]
Indeed. If others stumble upon this in the future: you can both monitor the number of connected peers, and the timestamps and heights of the chain. When the time approaches the current time, mining will begin.
