### ISSUE TITLE
Skepticoin dev discord

### ISSUE THREAD

**Issue by lk16** [skepticoin/skepticoin#46]
I have created a discord server a few weeks ago to discuss development for this project.

Sashimi was not sure about this, but I think this is the time.
We should have an easier way to communicate than PR's and issues.

What is the opinion of other devs here?

[Invite link](https://discord.gg/ekD6GtEn)

I currently mainly want to discuss development related stuff. 
Memers can be added down the road IMO.

If you want to join, please post your discord username in a reply.

@sashimi-houdini @atramos @dend456 @vitorgalvao @marekjedrzejewski

**Comment by atramos** [comment]
I would prefer to keep all code related discussions on GitHub. It's much easier to link to specific issues, PRs, and commits, and also easier for new developers to get involved.

**Comment by marekjedrzejewski** [comment]
I also think github is better for code related discussions, though something like discord could be useful for realtime discussion of skepticoin-whatever, but I'm not sure it's really needed at this stage.

Other thing is I'm using discord only once in a blue moon, and that's not something that would change it. If there was matrix bridge (for example via https://t2bot.io/discord/), I'm willing to lurk there sometimes.
