### ISSUE TITLE
supply-chain centralization vulnerability in initial download of peers.json

### ISSUE THREAD

**Issue by atramos** [skepticoin/skepticoin#48]
When launching Skepticoin Client the first time, without a peers.json, the client downloads the initial peer list from https://pastebin.com/raw/CcfPX9mS

This is a vulnerability as we don't know who all control the contents of this URL and what would happen if they stop updating it, or even worse, the contents get maliciously updated due to a hack.

The Skepticoin Client should accept a list of trusted peers.json URLs which are maintained by the Skepticoin Community.

**Comment by lk16** [comment]
I noticed this too and wondered why the initial peers.json is not just included in the repo.

**Comment by atramos** [comment]
Including it in the repo is bad too. It should be a runtime parameter with defaults.

**Comment by atramos** [comment]
Also BTW, the one on pastebin appears to be currently broken. None of those peers are active.

**Comment by lk16** [comment]
@sashimi-houdini I believe you are in control of those peers, can you have a look please.

**Comment by atramos** [comment]
I've started publishing an updated `peers.json` here in case anybody needs a work-around:
http://skepticoin.s3.amazonaws.com/peers.json

**Comment by lk16** [comment]
> The Skepticoin Client should accept a list of trusted peers.json URLs which are maintained by the Skepticoin Community.

I agree It's not super pretty, but it's an improvement over what we have now: 
* Everyone can suggest changes
* When changes are made, we can see who did it and when
* This satisfies the "maintained by skepticoin community" as mentioned above

> Including it in the repo is bad too. 

Could you elaborate on why this is bad and how precisely we should do it instead?

**Comment by atramos** [comment]
Firstly, it's about the pace of change. Imagine a future when the skepticoin code is very stable and we are not constantly making new releases. But the peers.json will still be constantly changing. Are we going to make new releases just to update this file? 

Secondly, this file contains individual people's IP addresses. In some countries and some jurisdictions, this comes with legal requirements, for example the right to have it deleted. It could become a huge headache to have it permanently stored in git history.

**Comment by lk16** [comment]
Okay, the former is not the case, however the latter makes sense.

So how should we share this list of peers instead? Where should it be hosted? Who should be able to change it?

**Comment by atramos** [comment]
The client should accept a list of URLs and merge the contents on start-up. For now it could default to the original from pastebin plus the one given above. In the future, new URLs can be added to the default list. Keep in mind that security is achieved by having at least one correct file. If one of them is invalid or outdated it'll just be ignored. So it's not necessary to control who will be able to change the contents, beyond ensuring that they are sourced from more than one person.

**Comment by lk16** [comment]
Sounds reasonable to me. Do you want to implement this or should I do it?

**Comment by atramos** [comment]
I think this is an important change, especially if the bad pastebin contents is causing new users to be unable to get started. But I probably won't be able to work on the code again until the weekend, so please feel free to jump in if you have the time sooner.

**Comment by sashimi-houdini** [comment]
Remember that [the 5th principle of cryptocurrency is to betray your core principles](https://github.com/skepticoin/skepticoin/blob/431720ee56af2d3023ee845fe17e1a844253bb58/docs/philosophy/principles.md), in this case decentralization. Note that many "real" cryptocurrencies have actual IP addresses hardcoded in the repo. Having said that, I'm happy to seriously look at any better solution than what we have now.

**Comment by sashimi-houdini** [comment]
If we're talking security, and known peers, it should also be noted that, when requesting a list of peers, the current implementation basically takes any peer at their word as to the truthfulness of the answer. I'm sure "more serious" cryptocurrencies have checks and balances built in (and banscores) in that area too.

**Comment by atramos** [comment]
I support lk16's PR#55. It would be funny, and awesome, if skepticoin is in some ways more secure than established crypto.
