### ISSUE TITLE
Wallet lookup gist throws error (name 'wallet' is not defined)

### ISSUE THREAD

**Issue by hunter-bidens-laptop** [skepticoin/skepticoin#5]
## Summary

The recommended [wallet lookup gist](https://gist.github.com/sashimi-houdini/cbb910f9a9fbd55b41f313fc057979fc) yells about name 'wallet' is not defined.

## Success Criteria

Provide a method to lookup wallet balance.

## Backup

Error screenshot:

![image](https://user-images.githubusercontent.com/83688753/117398442-01166500-aec4-11eb-93b8-60b1469fff9d.png)

**Comment by sashimi-houdini** [comment]
The gist is now fixed. I'll add a separate command `skepticoin-balance` (not yet released) as well for convenience.
