### ISSUE TITLE
Add more people with merge permissions

### ISSUE THREAD

**Issue by lk16** [skepticoin/skepticoin#51]
Currently there are 7 open PR's ready to be reviewed and merged.

We are piling up, which is both good and bad.
It's good to have people play around with the code, fix bugs and add features.
And it's bad because it will take more time to resolve conflicts as more pending PR's are made.

@sashimi-houdini I suggest to add more people to get merge permissions, so we can move faster.

Obviously I volunteer myself. Maybe @atramos is also interested?

And no, I don't intend to merge my own work without others having looked at it. Maybe we can require at least one approval from another contributor? (Does github support that? I'm not too familiar with this platform.)

In any case, I think it's best to review/merge PR's in the order that they were submitted.

**Comment by sashimi-houdini** [comment]
I'm seriously considering this

**Comment by sashimi-houdini** [comment]
ok @lk16 you'll be our @gavinandresen. I'm trusting you will only abuse your powers once I've mysteriously disappeared.

**Comment by sashimi-houdini** [comment]
I might add @atramos too if they so desires, but probably only after they have some code in the codebase through an accepted PR.

**Comment by lk16** [comment]
Nice, thanks.

So do we have some procedure for PR's? Like the approval thing I mentioned above?

**Comment by atramos** [comment]
I don't mind helping out. The more contributors we have, the sooner we can have a disagreement and a fork ;-)

**Comment by sashimi-houdini** [comment]
> So do we have some procedure

I'm happy with "let's informally require one reviewer (not yourself) for any non-trivial PR".

I haven't checked if Github supports technological enforcement for this, but I also don't care too much... let's be grown up here and just trust that this works. Crypto is _trustless_, after all

**Comment by atramos** [comment]
I think we can close this now as it appears @lk16 and I both have Merge permissions. Just to refine the "some procedure" a bit, I propose that after the "one reviewer (not yourself)" approves the PR, the original PR submitter ("yourself") is then responsible for merging verifying release-readiness of the master branch.
