### ISSUE TITLE
Add instructions for pre-commit hooks and mypy

### ISSUE THREAD

**Issue by lk16** [skepticoin/skepticoin#52]
I added `pre-commit-config.yaml` in #16, however this is not documented currently.

**Comment by sashimi-houdini** [comment]
You once wrote the following about it:

Pre-commit hooks can be set up with pre-commit install (after pip install pre-commit)
After that the hooks will run automatically on each commit.
If a check fails the commit doesn't go through, so it effectively enforces that the checks pass on new commits.
Of course there is a bypass git commit <other flags> --no-verify which shouldn't be used IMO.

Feel free to put those notes (or similar ones) in CONTRIBUTING.md

**Comment by lk16** [comment]
Yes, this was issue a reminder for myself mostly.
