### ISSUE TITLE
Release v0.1.15

### ISSUE THREAD

**Issue by lk16** [skepticoin/skepticoin#62]
We've achieved quite a lot since last release:
* Loading chains faster from disk
* Load initial peers from multiple URL's
* Cleaner multi-process mining

What do we need in order to push out the next release?

I would like to have these fixed:
* #54 ValueError: Invalid descriptor: -1 
* #25  Too many open files 

Opinions? @atramos @sashimi-houdini

**Comment by atramos** [comment]
My opinion is "Ship It!". Many users currently impacted by fixed issues, see recent comment traffic in #1.

**Comment by sashimi-houdini** [comment]
I'm quite happy to just release "now"; and release again when the other issues are fixed. I'll get to it.

**Comment by sashimi-houdini** [comment]
https://pypi.org/project/skepticoin/0.1.15/

As per usual, I just "shot from the hip" by running the tag and upload commands straight from master without any checks.
