### ISSUE TITLE
Miner stats don't report mined blocks

### ISSUE THREAD

**Issue by lk16** [skepticoin/skepticoin#64]
Running v0.1.15, mining on 4 processes.

```
miner 3 found block: 00085200-000042332522a07c638e297befae59785540dd9a0bd7c022f4c820b963eb66ff
2021-06-07 10:18:52 | uptime: 0:37:00 |  45 hash/sec | mined:   0 SKEPTI |  0.00 SKEPTI/h
```

**Comment by lk16** [comment]
I found out this is just a symptom of a bigger problem.

The network thread seems to crash with multiple KeyErrors like this once a block is mined:

```
Traceback (most recent call last):
  File "/home/luuk/projects/skepticoin-mining/venv/lib/python3.8/site-packages/skepticoin/networking/peer.py", line 148, in broadcast_message
    peer.send_message(message)
  File "/home/luuk/projects/skepticoin-mining/venv/lib/python3.8/site-packages/skepticoin/networking/peer.py", line 460, in send_message
    self.check_message_backlog()
  File "/home/luuk/projects/skepticoin-mining/venv/lib/python3.8/site-packages/skepticoin/networking/peer.py", line 465, in check_message_backlog
    self.start_sending()
  File "/home/luuk/projects/skepticoin-mining/venv/lib/python3.8/site-packages/skepticoin/networking/peer.py", line 468, in start_sending
    self.local_peer.selector.modify(self.sock, selectors.EVENT_READ | selectors.EVENT_WRITE, data=self)
  File "/usr/lib/python3.8/selectors.py", line 379, in modify
    raise KeyError(f"{fileobj!r} is not registered") from None
KeyError: "<socket.socket fd=100, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.10.144', 51304), raddr=('18.117.141.24', 2412)> is not registered"

** snip more KeyError stacktraces with different ip address / port combinations **

miner 0 found block: 00085296-00002369321d709ea6faf7dd7ad95afafd576bc812a85d1786b09f7ddb9edfbb
```

The following is speculation:
* The NetworkThread dies (but how does it show multiple KeyErrors then?)
* This causes chain height to not be updated for miners
* Miner(s) keep mining at same height
* Miner(s) end up mining various blocks at same height (I have evidence for this in the `chain` folder, also observed in #66)

**Comment by atramos** [comment]
I have not seen this error. But also all my mining is single-threaded across multiple machines. So I'll hypothesize there is a race condition somewhere when updating all the various Dict[]s that make up the blockchain pseudo-database.

**Comment by lk16** [comment]
I don't think there's a race condition in the blockchain dictionaries, because those are in CoinState and there is only one CoinState object, which is part of MinerWatcher. 

I think this is one of the many bugs related to peers and networking.

**Comment by atramos** [comment]
There are not many peers today. I think it's just you, me, and sashimi. And sashimi doesn't have a static IP address.

**Comment by atramos** [comment]
Hi @lk16. I've been running a multi-thread miner for the last 12 hours and have not seen this error.
Could this be caused by a corrupted blockchain in your machine, same as issue #66?

**Comment by lk16** [comment]
I haven't seen this one in a while either. Let's close it.
