### ISSUE TITLE
Balance command KeyError

### ISSUE THREAD

**Issue by lk16** [skepticoin/skepticoin#66]
On v0.1.15:

```
$ skepticoin-balance 
Reading cached chain
Reading chain from disk, starting height=85544, fresher=105
Traceback (most recent call last):
  File "/home/luuk/projects/skepticoin-mining/venv/bin/skepticoin-balance", line 8, in <module>
    sys.exit(main())
  File "/home/luuk/projects/skepticoin-mining/venv/lib/python3.8/site-packages/skepticoin/scripts/balance.py", line 23, in main
    coinstate = read_chain_from_disk()
  File "/home/luuk/projects/skepticoin-mining/venv/lib/python3.8/site-packages/skepticoin/scripts/utils.py", line 115, in read_chain_from_disk
    coinstate = coinstate.add_block_no_validation(block)
  File "/home/luuk/projects/skepticoin-mining/venv/lib/python3.8/site-packages/skepticoin/coinstate.py", line 179, in add_block_no_validation
    unspent_transaction_outs = self.unspent_transaction_outs_by_hash[block.previous_block_hash]
KeyError: b'\x00\x00>\xe45E\x8ck,\x13\xa8\xf1\x92\x10\xcam\x98\xe6z\x0b\xdf\xf9\xbc\xf8W(\x9b\xefD\xe1\x1e\xe7'
```

Running the command again gives the same result.

**Comment by atramos** [comment]
"Previous block hash not found in unspent_transaction_outs_by_hash"?

Just trying to understand this error. A transaction is trying to spend from a block that doesn't exist? Could it be caused by a fork? Maybe we're seeing some network partitioning due to the peering issues. 

This is all speculation, I haven't looked at the code. Try launching a fresh instance without a blockchain, then compare your blockchain to the downloaded one to see where they differ. You should be able to just diff the output of `ls`.

**Comment by atramos** [comment]
Still just thinking about this, not looking at the code, I think chain caching will not work well with blockchain forks, if you happen to cache the "losing" fork.

**Comment by atramos** [comment]
@lk16 @sashimi-houdini I'm thinking of a fix for this and it may required some lightweight local structured storage. Do you guys have a preference between LevelDB, SQLite, Berkeley DB, etc?

**Comment by lk16** [comment]
I found a folder `chain-old` inside my `chain` folder. Looks like some copy command I ran went wrong. 
The part that I can't explain is that this `chain/chain-old` folder has 14 blocks with the same height:
```
$ ls chain/chain-old/ | grep 00085200
00085200-00002ddd0853188046cd59b1759d71683a59b71bbdd5e37251c09ae2be3d63e7
00085200-0000381269efc7c897789916a5ba04e2e38cebe329004ae7bcf79bacd6bc784c
...
00085200-000143afb0e9b28a0676a9948e685ba3f64063364691f724dc0ee5131c7a2919
```

What I'll do next is remove all my chain files and see if that makes this problem disappear.

**Comment by lk16** [comment]
> Maybe we're seeing some network partitioning due to the peering issues.
I had 6 peers while re-downloading the last part of the chain, so we need to keep that in mind.

Anyway, after removing and re-downloading the chain, everything worked as it should.

Since we can't rule out that this issue happened because I messed up some copying commands and I can't reproduce the problem, I'll close this.
