### ISSUE TITLE
No such file or directory: 'peer_urls.txt'

### ISSUE THREAD

**Issue by marekjedrzejewski** [skepticoin/skepticoin#67]
Looks like installing from pip doesn't provide peer_urls.txt, which is required in latest skepticoin version.

**Comment by lk16** [comment]
I will provide a fix for this one. For the time being, this is the content of peer_urls.txt:
```
https://pastebin.com/raw/CcfPX9mS
https://skepticoin.s3.amazonaws.com/peers.json
```
