### ISSUE TITLE
Wallet Balance never actually goes up

### ISSUE THREAD

**Issue by Franklin-oss** [skepticoin/skepticoin#7]
![image](https://user-images.githubusercontent.com/65860526/117461541-4fcb0a00-af6b-11eb-8d0e-a07843f48bed.png)

**Comment by Franklin-oss** [comment]
Also btw I think mining is the only way to check wallet balance. You really gotta change that

**Comment by Franklin-oss** [comment]
![image](https://user-images.githubusercontent.com/65860526/117466945-dcc49200-af70-11eb-8f64-c61497a42c90.png)
what is this??!?!?!

**Comment by Franklin-oss** [comment]
> ![image](https://user-images.githubusercontent.com/65860526/117466945-dcc49200-af70-11eb-8f64-c61497a42c90.png)
> what is this??!?!?!

wallet balance seems random. Im starting to think this is a trojan

**Comment by allthetimeintheworld** [comment]
Seems to be the hash difficulty followed by block id no?

**Comment by 12341231211** [comment]
The first number in the FOUND message is the block #, yours is in the 13000s when the blockchain is up to 56000. You solved a block that was already solved. Rerun the mining script and let the blockchain update all the way, it will take a while.

**Comment by mplantsheer** [comment]
> The first number in the FOUND message is the block #, yours is in the 13000s when the blockchain is up to 56000. You solved a block that was already solved. Rerun the mining script and let the blockchain update all the way, it will take a while.

correct answer

**Comment by sashimi-houdini** [comment]
The correct answer has been mentioned already. A little bit more info copied from Reddit:

> Another short Q&A from the chat, taking it here so that others may learn from it as well:
> 
> Q\] I kinda noticed something weird. If someone were to mine more than one block, their wallet balance won't go up. It will remain stuck at 10. Might wanna check that out.
> 
> A\] This can happen if your blocks get "orphaned". It means the network picks up on a competing block that was found around the same time as yours. Bad luck. Though setting up [port forwarding](https://github.com/skepticoin/skepticoin/blob/master/docs/port-forwarding.md) helps, because you become better connected and the rest of the network is more likely to see your block first.
> 
> If you feel adventurous (more for learning than anything else) you can play around in the REPL or the command line to find out what happened.  When you find a block its hash is printed on screen. You can dig around in the `coinstate` object to try to find it.
> 
> Even easier: just look in the directory "chain", for the height-hash combination printed on screen. At the same height, you'll likely see another block, which tells you you lost the race.
