### ISSUE TITLE
Emergency release v0.1.16

### ISSUE THREAD

**Issue by lk16** [skepticoin/skepticoin#73]
The "shot from the hip" missed its target. v0.1.15 is pretty broken.

I suggest merging the two below and doing an emergency release:
* #68 move peer_urls.txt to python code, without this new users can't connect to the network
* #70 prevent too many open files error on non-windows platforms, which breaks network related code badly

@sashimi-houdini @atramos

**Comment by lk16** [comment]
I've spotted more bugs already, but at least the miner stays alive for a few hours on my #70 branch.

**Comment by atramos** [comment]
I vote Ship It! After we get to a functioning release, we should slow down and establish a process to validate basic functionality.

**Comment by lk16** [comment]
Hold on, I'm wrapping up #70 right now. I fixed logging in MinerWatcher too, which was apparently broken. Args were ignored completely.

**Comment by lk16** [comment]
#70 is merged now. Not sure how releasing works or if I have perms to do it.

@sashimi-houdini

**Comment by atramos** [comment]
@lk16 @sashimi-houdini please include PR#75 fix to issue#71, it's a big one.

**Comment by lk16** [comment]
#75 was merged.
@sashimi-houdini  time for a release?

**Comment by atramos** [comment]
Is this the time in Skepticoin history when the original founder disappears? @lk16 we'll need to study up and see how Bitcoin handled it 😆

**Comment by lk16** [comment]
I'll summon atramos like last time. I have some ideas if that won't work.

**Comment by lk16** [comment]
I got perms to release on pypi, so I just did. I also [announced](https://www.reddit.com/r/skepticoin/comments/o0iu3w/skepticoin_v0116_released/) the release on reddit.
