### ISSUE TITLE
Wallet lookup gist throws error "name 'get_coinstate' is not defined"

### ISSUE THREAD

**Issue by hunter-bidens-laptop** [skepticoin/skepticoin#8]
## Summary

Wallet lookup [gist ](https://gist.github.com/sashimi-houdini/cbb910f9a9fbd55b41f313fc057979fc)throws error (shown in the screenshot in the backup)

## Success Criteria

Users are able to look up wallet balance.

## Backup

![image](https://user-images.githubusercontent.com/83688753/117463167-fdf79500-af14-11eb-888b-b8095cb1cfe0.png)

**Comment by asimmon** [comment]
When I look at [balance.py](https://github.com/skepticoin/skepticoin/blob/9556a2fd4202dbe0e76d0daa02b872bcaefcd38a/skepticoin/scripts/balance.py) it seems that the gist should looks like this:

```
>>> from skepticoin.scripts.utils import open_or_init_wallet
>>> from skepticoin.scripts.utils import read_chain_from_disk
>>> from skepticoin.params import SASHIMI_PER_COIN
>>> coinstate = read_chain_from_disk()
>>> wallet = open_or_init_wallet()
... (redacted) ...
>>> print(wallet.get_balance(coinstate) / SASHIMI_PER_COIN)
... (redacted) ...
```

**Comment by sashimi-houdini** [comment]
@asimmon the gist was already updated as you suggested, but the screenshot was reflective of the old situation.
