### ISSUE TITLE
Bad Peer 127.0.0.1

### ISSUE THREAD

**Issue by lk16** [skepticoin/skepticoin#84]
I run 4 miners and got this after a few hours of mining. 
Should we hardcode to not connect to ourselves?

```
Bad Peer (disconnected without hello): 127.0.0.1                                                                                                               
Bad Peer (disconnected without hello): 127.0.0.1                                                                                                               
Bad Peer (disconnected without hello): 127.0.0.1                                                                                                               
Bad Peer (disconnected without hello): 127.0.0.1 
```

**Comment by atramos** [comment]
I'd like to find out why it's even trying, and fix the root cause instead if possible.

**Comment by atramos** [comment]
I think this might be caused by one of the unit tests, which is invoked in the git commit-hook, connecting to the "production" skepticoin peer network and broadcasting the "127.0.0.1".

**Comment by atramos** [comment]
related: #54

**Comment by atramos** [comment]
The fix for this is going to be tricky, because a simple fix breaks the tests.

**Comment by atramos** [comment]
Actually, not so tricky. Ultimately this was caused by removing the peers.json update out of DiskInterface.

**Comment by sashimi-houdini** [comment]
Closed this to reflect my understanding of @refacktor's remark above
