### ISSUE TITLE
downloading fresh chain from network takes too long even when everything is working correctly

### ISSUE THREAD

**Issue by atramos** [skepticoin/skepticoin#87]
This has been mentioned in #1.
Some rough metrics, calculated on my head and without using a timing device:
- Chain download speed "feels like" about 10 blocks per second or less
- That translates to over 1 minute for each day that the chain is old, to catch up
- The latest chain.zip is from mid-May
- So we're looking at 1-2 hours before a fresh install can start mining.

**Comment by atramos** [comment]
I have narrowed down the slowness to `handle_inventory_message_received` in `remote_peer.py`. Currently after receiving the "inventory" consisting of a list of 500 hashes, this code requests just one block at a time, waiting until the block is received before requesting the next one. Due to the asynchronous state machine style of this code, the necessary change is not obvious.

**Comment by lk16** [comment]
I think it's time to update the zip file. I will see if I have perms for that.

**Comment by atramos** [comment]
The open PR increases the chain download speed to over 150-200 blocks per second. We should phase out the zip file, as it complicates any solution to issue #80.
