### ISSUE TITLE
Usage guide should teach how to list wallet addresses and find balance in each wallet address

### ISSUE THREAD

**Issue by metaperl** [skepticoin/skepticoin#9]
How do I list my wallet addresses?

How do I see the balance in each address?

Shouldnt there be an introductory usage guide that teaches this? It is not in the README.

**Comment by sashimi-houdini** [comment]
Though it doesn't mention commands for listing, I think the [wallet documentation](https://github.com/skepticoin/skepticoin/blob/master/docs/wallet.md) will be helpful for you.
