### ISSUE TITLE
Better exception handling

### ISSUE THREAD

**Issue by lk16** [skepticoin/skepticoin#91]
Currently we do things like 

```py
try:
    ...
except Exception as e:
    raise Exception(...) from e
```

We should introduce some Exception classes, probably in a separate `exceptions.py`.
That way we don't have to continue this ugly and potentially faulty pattern.

**Comment by sashimi-houdini** [comment]
I'm going to close this as to generic; if you have specific PRs for specific locations where this should be fixed I can always reconsider.
