### ISSUE TITLE
the thousands of files in the chain/ folder are no longer needed

### ISSUE THREAD

**Issue by atramos** [skepticoin/skepticoin#94]
@lk16 asked: Shouldn't we just delete the chain folder? Once [PR #90] is released and end-users start using this, we may as well make this change convenient for them.

_Originally posted by @lk16 in https://github.com/skepticoin/skepticoin/pull/90#discussion_r662115836_

**Comment by atramos** [comment]
This issue only impacts existing **users of skepticoin version is 0.1.17 or earlier** who upgraded to 0.1.18 or later:

The chain folder was used in the earlier versions of skepticoin. It contained one file for every block in the chain -- approaching 100,000 files as of this writing.

Post-PR #90  versions of skepticoin just use two files: `chain.zip` and `chain.cache`

This issue has been created to document the answer for users who may ask in the future, why they have so many old files in the chain folder. Also, the application will now print a warning telling the user to manually delete the folder. 

I don't think we should automatically delete the files, because 1) Some users might decide they want the option to revert to an old version of skepticoin, 2) Deleting 100,000 files is very slow, 3) Deleting 100,000 files at once could trigger anti-malware software for some users, creating confusion.

**Comment by atramos** [comment]
Tagged as `question` for @lk16. Do you agree?

**Comment by lk16** [comment]
Sure, works for me. I was mostly pointing it out to hear some rationale behind your changes in #90. 

Hopefully more people will start using skepticoin in the future, so this will only affect a very small subset of our users.
