### ISSUE TITLE
Investigate if MinerWatcher slows down mining with many cpus

### ISSUE THREAD

**Issue by lk16** [skepticoin/skepticoin#95]
I want to make sure that MinerWatcher is not slowing down mining, since with many cpu's it needs do do a lot of bookkeeping.

I got a new pc with 16 cores / 32 threads, so I'll probably look into this one myself.

**Comment by atramos** [comment]
I did some very casual quick measurements. The overhead seems minimal. You get linear scaling per number of actual cores, and hyper threads don't count for much.
