### ISSUE TITLE
Release 0.1.17

### ISSUE THREAD

**Issue by lk16** [skepticoin/skepticoin#98]
@atramos I haven't contributed much lately, so question for you: is master stable enough for a release?

I hear people really want the faster block download fix.

In case you missed it, we have a discord now, which is mostly troubleshooting. See this [announcement](https://www.reddit.com/r/skepticoin/comments/ocex3a/we_created_a_skepticoin_discord/).
In case you join, let me know, so I can give you the "maintainer" role.

**Comment by atramos** [comment]
My production miners are running on the branch from PR #89. I recommend merging that before release. It addresses the exponential growth in failed connections to dead and outbound-only peers.

**Comment by lk16** [comment]
I approved #89, please merge. I plan to do a release early next week.

**Comment by lk16** [comment]
I published the release.

**Comment by lk16** [comment]
I messed up the release, so I made a new one with version 0.1.18.

**Comment by atramos** [comment]
Also just a quick note, I didn't get around to meeting PR #89, so the soft-ban stuff is not in this release.
